version: 2.1
executors:
  php73:
    docker:
      - image: vesica/php73:dev
      - image: memcached:1.5
      - image: redis:5
      - image: percona:5.7
        environment:
          - MYSQL_USER: circleci
          - MYSQL_PASSWORD: circleci
          - MYSQL_ROOT_PASSWORD: circleci
          - MYSQL_DATABASE: circleci
    working_directory: ~/repo

jobs:
  build-app:
    executor: php73
    steps:
      - checkout
      - run: composer install
      - run: vendor/bin/phpunit --debug

workflows:
  version: 2
  build-master:
    jobs:
      - build-app:
          filters:
            branches:
              only: master
  build-tags:
    jobs:
      - build-app:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/